# Generated by Django 4.2.4 on 2025-04-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0002_post_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lawyer_type', models.CharField(choices=[('NGO', 'Non-Governmental Organization'), ('Non-Profit', 'Non-Profit'), ('Profit', 'Private Firm / Individual')], max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=15)),
                ('rating', models.FloatField(default=0.0)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
